version: 2
updates:
  # bun dependencies
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "16:00"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    pull-request-branch-name:
      separator: "/"
    commit-message:
      # :arrow_up: for ⬆️
      prefix: "chore(deps): ⬆️ "

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "16:00"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
