export const REVIEW_RESPONSE_JSON_START_MARKER = "[COPILOT_JSON_START]";
export const REVIEW_RESPONSE_JSON_END_MARKER = "[COPILOT_JSON_END]";
export const REVIEW_PENDING_POLL_INTERVAL_MS = 30_000;

export const CLI_COLOR_ENV_DEFAULTS = {
  FORCE_COLOR: "1",
  COLORTERM: "truecolor",
  TERM: "xterm-256color",
} as const;
